#! /usr/bin/env bash
# Copyright 2024 Raphael Thomazella. All rights reserved.
# Use of this source code is governed by the BSD-3-Clause
# license that can be found in the LICENSE file and online
# at https://opensource.org/license/BSD-3-clause.

### options, imports, mocks ###

set -euo pipefail
shopt -s globstar
source "$PWD/lib.sh"
trap 'err $LINENO' ERR

##########################
### vars and functions ###
##########################

# Description: Print script usage
# STDOUT     : Help message
usage() {
  command cat <<-EOF
Usage:
Generate mockery mocks and apply some modifications to the generated files
EOF
}

# Description: Saves mockery version to a file
# Sideeffects: Creates a file named .mockery-version
save_mockery_version() {
  version=$(mockery --version 2>/dev/null)

  printf %s\\n "$version" >.mockery-version
}

# Description: Modify generated files to remove version
# Sideeffects: Modifies files in place
strip_version() {
  local mockeryGeneratedRegex="generated by mockery v[0-9]+\.[0-9]+\.[0-9]+"
  find . -name "mock*.go" -exec "$SED" --in-place --regexp-extended -e "s/$mockeryGeneratedRegex/generated by mockery/" {} \;
}

# Description: Modify generated files to rename EXPECT to Expect
# Sideeffects: Modifies files in place
rename_expect() {
  find . -name "mock*.go" -exec "$SED" --in-place --regexp-extended -e "s/EXPECT/Expect/" {} \;
}

##############
### script ###
##############

if requested_help "$*"; then
  usage
  exit 1
fi

mockery
save_mockery_version
strip_version
rename_expect
