name: release
run-name: release ${{ github.ref }}@${{ github.sha }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Push tag
        shell: bash
        env:
          CHANGELOG_FILE: CHANGELOG.md
          BASH_ENV: ./lib.sh
          DRY_RUN: false
          TAGS_FILE: tags.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./workflows/release/tag.sh
