name: release
run-name: release ${{ github.ref }}@${{ github.sha }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push tag
        shell: bash
        env:
          CHANGELOG_FILE: CHANGELOG.md
        run: ./sh/workflows/release/tag.sh
